apiVersion: 1

datasources:
  - name: Azure Monitor
    type: grafana-azure-monitor-datasource
    access: proxy
    jsonData:
      tenantId: <tenant-id>
      clientId: <client-id>
      clientSecret: <client-secret>
      subscriptionId: <subscription-id>
      cloudName: 'azuremonitor'
    isDefault: false
