apiVersion: 1

datasources:
  - name: Google Cloud Monitoring
    type: stackdriver
    access: proxy
    jsonData:
      authenticationType: jwt
      clientEmail: <service-account-email>
      privateKey: <private-key>
      defaultProject: <project-id>
    isDefault: false
