# Prometheus configuration for GCP (Google Managed Service for Prometheus)
global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

remote_write:
  - url: https://monitoring.googleapis.com/v1/projects/<project-id>/locations/global/prometheus/api/v1/write
    oauth2:
      client_id: <client-id>
      client_secret: <client-secret>
      token_url: https://oauth2.googleapis.com/token
